### PR TITLE
Allow environment variables

### PR DESCRIPTION
**Pull request by sdebruyn**
See https://github.com/Runnable/validate-dockerfile/issues/17

### CODE REVIEW

**Comment by bkendall** [comment]
thanks for making this a PR, @SamuelDebruyn. I was about going to comment on the issue, but I guess I'll continue the conversation here.

My first instinct is that I'm not really a fan of replacing all the env variables with strings and continuing to validate them. I would rather acknowledge that there's an env variable there and that the line is valid (regardless of the value of the variable).

Second, the documentation for Docker states:

> Environment variables (declared with the ENV statement) can also be used...

Do you think that this is sufficient (just acknowledging that envs are present), or do you think this should go a step further and validate that any env variable used in a command in the Dockerfile was declared with an `ENV` statement before it? I think if we were to do this 'extra' validation, we would need to only consider it a warning as prior images (i.e. `FROM [image]`) _could_ have declared a variable that we wouldn't see in the Dockerfile being validated.

**Comment by SamuelDebruyn** [comment]
Well, I couldn't figure out how to include `\${?[a-zA-Z_]+[a-zA-Z0-9_]*(:(\+|-)[a-zA-Z0-9_]*)?}?` in a regex like `/^[a-z_][a-z0-9_]{0,30}$/` because you could have as much variables as you want in there and you can't define a group inside a character set... That's why I went for this approach.

Note that my regex for detecting environment variables isn't perfect either, because a regex by itself can't detect matching braces.

On the one hand, as [stated before](https://github.com/Runnable/validate-dockerfile/issues/1#issuecomment-53620316), this is simply a linter and should not care about the state of the system. On the other hand, the env vars *should* be defined somewhere in the Dockerfile (or the one in the `FROM` statement) and a Dockerfile *should* be marked as invalid if it contains illegal statements.

I suggest adding a warning, but exiting with a successful exit code if an env var is referenced but not explicitly set with `ENV`.

**Comment by SamuelDebruyn** [comment]
Would you like me to reset/revert that last commit (and put it on another branch) so my PR only includes the test cases?

**Comment by SamuelDebruyn** [comment]
Any update on this? Should I resolve merge conflicts so this can be merged? Should I revert that last commit first?

**Comment by bkendall** [comment]
LGTM.

**Pull request merged**
